# docker-compose.test.yml
version: '3.8'

services:
  # 1. The Fake ElastiCache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5

  # 2. Your Application Running Tests
  app-test:
    build: .
    environment:
      - PORT=3002
      - REDIS_HOST=redis 
      - TEST_MODE=integration 
    depends_on:
      redis:
        condition: service_healthy
    command: ["npm", "test"]